# makefile
# use to compile and test 



RunProcessor: Processor.cpp ALU.cpp ALUControl.cpp ControlUnit.cpp DataMemory.cpp InstructionMemory.cpp Multiplexor.h Parser.cpp PC.h RegisterTable.cpp ShiftLeftTwo.cpp SignExtend.cpp Opcode.cpp
	g++ -std=c++11 -Wall Processor.cpp ALU.cpp ALUControl.cpp ControlUnit.cpp DataMemory.cpp InstructionMemory.cpp Multiplexor.h Parser.cpp PC.h RegisterTable.cpp ShiftLeftTwo.cpp SignExtend.cpp Opcode.cpp 


